//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIMSDBEntities : DbContext
    {
        public TIMSDBEntities()
            : base("name=TIMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcademicLevel> tblAcademicLevels { get; set; }
        public virtual DbSet<tblCourse> tblCourses { get; set; }
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblTraineeCourse> tblTraineeCourses { get; set; }
        public virtual DbSet<tblTraineeMessage> tblTraineeMessages { get; set; }
        public virtual DbSet<tblTraineePayment> tblTraineePayments { get; set; }
        public virtual DbSet<View_TraineeCourseList> View_TraineeCourseList { get; set; }
        public virtual DbSet<View_TraineeList> View_TraineeList { get; set; }
        public virtual DbSet<View_TraineeMessageList> View_TraineeMessageList { get; set; }
        public virtual DbSet<View_TraineePaymentList> View_TraineePaymentList { get; set; }
        public virtual DbSet<View_TraineeCourseCost> View_TraineeCourseCost { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
        public virtual DbSet<tblTrainee> tblTrainees { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
