//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TraineePaymentList
    {
        public string Fullname { get; set; }
        public string Course { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Duration { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
    }
}
