//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TraineeList
    {
        public string Fullname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string AcademicLevel { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] Photo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
